### PR TITLE
Modernizations

### PR DESCRIPTION
**Pull request by akx**
This PR:

* runs the pyupgrade and flynt tools to fix up minor legacy things
* gets rid of setup.py in favor of a declarative setup.cfg
  * this also gets rid of the importlib.metadata runtime dependency; the single source of version truth is PEP 440 `__version__`
* implements a couple other small incidental fixes

### CODE REVIEW

**Comment by akx** [comment]
@dyve You could have let me know you'd prefer separate PRs of the features, I would've had no problem cherry-picking them :-) (I'm a bit disappointed that the commits in the new PRs lost all attribution...)

**Comment by dyve** [comment]
@akx I didn't realize that, apologies. I'm struggling with the declarative setup.py, if you'd reconstruct this PR to handle just that, then at least we can keep attribution intact for this PR. If it's important to you, I'd also be happy to accept PR's that touch the other code you contributed. I have mentioned you in all the separate PR's.

**Comment by dyve** [comment]
@akx Anything I can do to remedy this?

**Comment by akx** [comment]
@dyve Don't worry about it, it's not a big deal! :)

I'll close this and make a separate rebased PR of the declarative setup.cfg stuff :)

**Pull request closed without merging**
