### PR TITLE
Remove <nav> from pagination

### LINKED ISSUE #449: Missing aria-label on pagination <nav> element
Since #60, pagination is wrapped in a `<nav>` element. This is a good thing because screen reader users can find the pagination quickly via a landmark. But it can also cause confusion because it is not clear which navigation landmark is which. The  [ARIA Authoring Practices Guide](https://www.w3.org/WAI/ARIA/apg/practices/landmark-regions/#generalprinciplesoflandmarkdesign) therefore recommends to add labels:

> If a specific landmark role is used more than once on a page, provide each instance of that landmark with a unique label.

I see 3 options how to fix this:

1. Provide a fixed label (e.g. "Pagination") along with translations
2. Add a `label` parameter to the  `bootstrap_pagination` template tag
3. Remove the `<nav>` element from django-bootstrap5 and tell authors to add it themselves

Which option do you think works best?

### PR DESCRIPTION
**Pull request by xi**
fixes #449

Providing a fixed label is not feasible because this project does not have any translations yet.

From the other two options, I guess that not having a `<nav>` element is better than having an unusable one.

### CODE REVIEW

**Comment by dyve** [comment]
Removing the nav would step away from the [best practice in Bootstrap examples](https://getbootstrap.com/docs/5.3/components/pagination/#overview) that we follow.

**Comment by dyve** [comment]
Perhaps a setting for `pagination_aria_label`?

**Comment by xi** [comment]
> Removing the `nav` would step away from the best practice in Bootstrap examples that we follow.

Not really. As explained in #449, the current implementation does not follow best practices because it does not contain a label.  Removing the `<nav>`  here and telling authors to add it themselves is the proper fix IMHO.

Adding a parameter would allow authors to fix this issue, but the default would still be broken. That's why it is not my preferred option. But if you really think that adding a parameter is the way to go, I can adapt the code accordingly.

**Comment by dyve** [comment]
I don't use screen readers myself. I can imagine that a `nav` without context is confusing, but that's about it. It would be really helpful to get feedback from someone that actually needs or benefits from this change.

**Comment by xi** [comment]
I sent  a mail to the Web Accessibility Initiative Interest Group Discussion list: https://lists.w3.org/Archives/Public/w3c-wai-ig/2024JulSep/0113.html

So far, both answers recommended to remove the `<nav>` element. Not just because of the missing label, but also because the question whether the pagination should be a landmark should be considered in the context of the whole page. For example, it would be bad if authors do not add any landmarks themselves and the pagination ends up being the only landmark on the page.

**Comment by dyve** [comment]
I'd say that settles is then. And we have documented the why and what in this issue. Thanks for all the effort you put into this @xi 🙏

**Pull request merged**
