### PR TITLE
Added `.form-label` default to `<label>`s.

### PR DESCRIPTION
**Pull request by emmceemoore**
It looks like [bootstrap 5 expects `.form-label` now on `<label>` elements](https://getbootstrap.com/docs/5.1/migration/#forms).

image

TESTING:
- Modified affected tests to reflect the newly added `.form-label` default.

### CODE REVIEW

**Comment by dyve** [comment]
Thanks, looks like we'll have to do quite a few fixes with all the breaking changes to forms.

**Comment by dyve** [comment]
The `label_class` in `render_label` was intended for horizontal forms (which it seems is now obsolete).

I'll check the new changes and see what we need to do. Thanks for the PR, and I'll reply here later.

**Comment by dyve** [comment]
For horizontal forms, we need `col-form-label`
https://getbootstrap.com/docs/5.1/forms/layout/#horizontal-form

**Comment by dyve** [comment]
Looks like this solution might be the only thing necessary after all, because most calls to `render_label` provide an explicit `label_class`. Still some checks to do, thanks for your patience.

**Comment by zyv** [comment]
Any news on that? After upgrading several of my Django apps from BS4 to BS5, I became very much convinced, that I don't want to render forms myself anymore and should switch to `django-bootstrapX`. It would be really good, however, if all breaking changes are taken care of.

**Comment by dyve** [comment]
Merging main in broke this.

**Comment by dyve** [comment]
Sorry for breaking this @emmceemoore. I'll pull this one in and fix it with a separate PR.

**Pull request merged**
