### PR TITLE
This is just a minor fix for issue #204, a typo made it .j" instead o…

### PR DESCRIPTION
**Pull request by di-delta9**
…f .js."

### CODE REVIEW

**Review by pep-idl — APPROVED** [review]
I had the same conclusion. Nice job, thanks! :)

**Review by pep-idl — APPROVED** [review]

**Comment by di-delta9** [comment]
Most welcome!! Thank you for pulling :)

**Comment by yaleman** [comment]
Can this be merged urgently, or the pypi release with the broken reference pulled?

**Comment by di-delta9** [comment]
I thought it already had been?

Pull from my repo if you require it right now:

https://github.com/di-delta9/django-bootstrap5

**Comment by yaleman** [comment]
It only got reviewed, not merged or released...

**Comment by di-delta9** [comment]
> It only got reviewed, not merged or released...

Yes I see this.
If you need a quick and dirty fix like I did first,
Go to your pip library path and fix the file itself, I suppose while we get a permanent merge:
You probably already know but the fix is is easy: you can modify the string in /lib/python3.9/site-packages/django_bootstrap5/core.py. the mistake is right there.

**Comment by yaleman** [comment]
I've already rolled back to an older version rather than making fun patches the norm in prod :)

**Review by dyve — APPROVED** [review]

**Comment by dyve** [comment]
Fixing in #224, thanks.

**Pull request closed without merging**
