### PR TITLE
Fix RadioSelectButtonGroup rendering and add 'disabled' attribute to radio button group template

### LINKED ISSUE #111: RadioSelectButtonGroup doesn't render
Our custom widget doesn't render because the `template_name` is overwritten in `renderers.py`.

### PR DESCRIPTION
**Pull request by Actionb**
Fixes #111 

Also edited the `RadioSelectButtonGroup` template so that the widget can be rendered as disabled.

### CODE REVIEW

**Comment by Actionb** [comment]
Little discussion: doesn't the template override in `FieldRenderer.add_widget_attrs` make it impossible for people to add & use their own bootstrap widget templates? 
Maybe refer to a different attribute for bootstrap specific templates?

```
class MyWidget(Widget):
    bootstrap_template_name = "templates/awesome_bootstrap_template.html"
```


Then `FieldRenderer.add_widget_attrs` could look something like this:

```
def add_widget_attrs(self):
    """Return HTML attributes for widget as dict."""
    if self.is_multi_widget:
        widgets = self.widget.widgets
    else:
        widgets = [self.widget]
    for widget in widgets:
        self.add_widget_class_attrs(widget)
        self.add_placeholder_attrs(widget)
        if not widget.bootstrap_template_name:
            if isinstance(widget, RadioSelectButtonGroup):
                widget.bootstrap_template_name = "django_bootstrap5/widgets/radio_select_button_group.html"
            elif isinstance(widget, (RadioSelect, CheckboxSelectMultiple)):
                widget.bootstrap_template_name = "django_bootstrap5/widgets/radio_select.html"
            elif isinstance(widget, ClearableFileInput):
                widget.bootstrap_template_name = "django_bootstrap5/widgets/clearable_file_input.html"
            else:
                widget.bootstrap_template_name = widget.template_name
```

**Comment by Actionb** [comment]
Fixed the code style issues. Should pass the tests now.

**Comment by Actionb** [comment]
To clarify:  #313 did **not** fix the issue. That PR only tweaked the template for the widget, but it did not fix the template being overriden in `renderers.py`. 

This is what the RadioSelectButtonGroup looks like currently in the example app:
django_bootstrap_radioselect_broken

This is what it looks like with the fix:
django_bootstrap_radioselect_fixed

**Comment by dyve** [comment]
Looking at this.

**Review by dyve — APPROVED** [review]

**Comment by truePhilipp** [comment]
Are there plans to merge this?

**Comment by dyve** [comment]
Yes, we can pull this in. Can you rebase with current main?

**Comment by truePhilipp** [comment]
I cannot, I don't have push rights to @Actionb fork...

**Comment by truePhilipp** [comment]
Cool, thanks.
Any idea when this will be available on pypi?

**Comment by calebsyring** [comment]
Looks like this was released in 24.1. Fix in my case was updating and changing our widget to inherit from [RadioSelectButtonGroup](https://github.com/zelenij/django-bootstrap-v5/blob/cab866f2f0744245fdda86e2d555f373d4f4a081/src/bootstrap5/widgets.py#L4).

**Pull request merged**
