### PR TITLE
Pass "horizontal_field_offset_class" to child renderers

### PR DESCRIPTION
**Pull request by vmullagaliyev**
The "horizontal_field_offset_class" doesnt pass to child renderers (from form to fields), so it actually does't work as described in documentation.

### CODE REVIEW

**Comment by dyve** [comment]
Could you add a regression test?

**Comment by dyve** [comment]
Good catch btw 👍

**Comment by paulocoutinhox** [comment]
merge pls

**Comment by dyve** [comment]
This change is still missing a test.

**Pull request closed without merging**
